name = "SpatialMath"
uuid = "657cd90f-b779-50a8-81d7-9e329df4af1b"
authors = ["AbdulrhmnGhanem <research@abdulrhmnghanem.tech>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
LinearAlgebra = "1.11.0"
Symbolics = "6.24.0"
julia = "1.10"
